### PR TITLE
Add all components to the Todos app

### PR DESCRIPTION
**Pull request by ivangonzalez224**
It's my Todos project and I added the following features:

- Added the nav bar component.
- Added the header component.
- Added the input component to add new entries in the list.
- Added the Todos logic component to display the item list dynamically.
- Added styles to all the components.

### CODE REVIEW

**Review by jlcarrascof — APPROVED** [review]
👏👏👏 💪

Congratulations, **@ivangonzalez224** 

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a4578596d45304d7a4e6b595451344e6a4e6a4f474530597a45795a6a63795a574d774f47526d4f546b784e7a56695a6a526c593255334d435a6c634

PR has a title and summary. ✔️
Professional README ✔️
App working properly ✔️
Correct Gitflow ✔️

Man, I personally give you my congratulations for your nice job.

Please read the additional comment about an observation that kindly you need to fix.

The project is **approved** and you can merge this branch and in a separate branch, please, kindly fix the menu options.

Congratulations, again!!! 

Your reviewer,

Javier.-

**Comment by jlcarrascof** [comment]
**OBSERVATIONS:**

Your app looks clear and according to the react tutorial. Merge this branch, please. 

Captura de pantalla 2023-08-14 a la(s) 17 47 19

**Comment by jlcarrascof** [comment]
**OBSERVATIONS:**

I noticed this menu as an unordered list. I kindly suggest, please, open another branch and fix this menu. That's all,man. Congrats, again. 


Captura de pantalla 2023-08-14 a la(s) 17 47 31

**Comment by ivangonzalez224** [comment]
Thank you for your feedback @jlcarrascof  😄

**Pull request merged**
